'use client';

import { useEffect, useMemo, useState } from 'react';

const modules = ['clientes', 'propiedades', 'cna', 'kpis', 'asesores', 'usuarios', 'red_contactos', 'facturacion', 'config_tenant'];
const actions = [['puede_leer', 'Leer'], ['puede_crear', 'Crear'], ['puede_editar', 'Editar'], ['puede_eliminar', 'Eliminar']];

export default function UsuariosPage() {
  const [users, setUsers] = useState<any[]>([]); const [roles, setRoles] = useState<any[]>([]); const [roleId, setRoleId] = useState('');
  const [query, setQuery] = useState(''); const [status, setStatus] = useState(''); const [roleFilter, setRoleFilter] = useState('');
  const [permissions, setPermissions] = useState<Record<string, Record<string, boolean>>>({}); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const [error, setError] = useState('');

  useEffect(() => { Promise.all([fetch('/api/usuarios').then((r) => r.json()), fetch('/api/roles').then((r) => r.json())]).then(([loadedUsers, loadedRoles]) => { setUsers(loadedUsers); setRoles(loadedRoles); }).catch((e) => setError(e.message || 'No se pudo cargar el módulo')).finally(() => setLoading(false)); }, []);

  const visibleUsers = useMemo(() => users.filter((u) => { const slug = u.roles?.[0]?.rol?.slug || 'sin-rol'; return (!query || `${u.nombre || ''} ${u.email}`.toLowerCase().includes(query.toLowerCase())) && (!status || String(u.activo) === status) && (!roleFilter || slug === roleFilter); }), [users, query, status, roleFilter]);
  function selectRole(id: string) { setRoleId(id); const role = roles.find((item) => String(item.id_rol) === id); const next: Record<string, Record<string, boolean>> = {}; modules.forEach((module) => { const current = role?.permisos?.find((p: any) => p.modulo === module) || {}; next[module] = Object.fromEntries(actions.map(([key]) => [key, Boolean(current[key])])); }); setPermissions(next); }
  async function savePermissions() { if (!roleId) return; setError(''); setMessage(''); const response = await fetch('/api/roles', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id_rol: Number(roleId), permisos: Object.entries(permissions).map(([modulo, values]) => ({ modulo, ...values })) }) }); const data = await response.json(); if (!response.ok) { setError(data.error || 'No se pudieron guardar los permisos'); return; } setRoles((current) => current.map((role) => role.id_rol === data.id_rol ? data : role)); setMessage('Permisos actualizados correctamente.'); }
  function togglePermission(module: string, action: string) { setPermissions((current) => ({ ...current, [module]: { ...current[module], [action]: !current[module]?.[action] } })); }

  return <main className="mx-auto max-w-7xl space-y-6 p-6 md:p-8"><header className="flex flex-col gap-4 border-b border-slate-800 pb-6 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-3xl font-extrabold">Usuarios y permisos</h1><p className="mt-1 text-sm text-slate-400">Administra accesos y permisos por rol.</p></div></header>
    {error && <p className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-300">{error}</p>}{message && <p className="rounded-lg border border-emerald-500/30 bg-emerald-500/10 p-3 text-sm text-emerald-300">{message}</p>}
    <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><div className="mb-4 flex flex-col gap-3 sm:flex-row"><div><h2 className="text-lg font-bold">Permisos por rol</h2><p className="text-sm text-slate-400">Selecciona un rol para configurar sus acciones.</p></div><select value={roleId} onChange={(e) => selectRole(e.target.value)} className="sm:ml-auto rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white"><option value="">Selecciona un rol...</option>{roles.map((role) => <option key={role.id_rol} value={role.id_rol}>{role.nombre}</option>)}</select></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-800/80 text-xs uppercase text-slate-400"><tr><th className="p-3 text-left">Módulo</th>{actions.map(([, label]) => <th key={label} className="p-3 text-center">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-800">{modules.map((module) => <tr key={module}><td className="p-3 capitalize text-slate-200">{module.replaceAll('_', ' ')}</td>{actions.map(([key, label]) => <td key={key} className="p-3 text-center"><input type="checkbox" aria-label={`${label} ${module}`} checked={Boolean(permissions[module]?.[key])} disabled={!roleId} onChange={() => togglePermission(module, key)} className="h-4 w-4 accent-amber-500" /></td>)}</tr>)}</tbody></table></div><div className="mt-4 flex justify-end"><button disabled={!roleId} onClick={savePermissions} className="rounded-lg bg-amber-500 px-5 py-2 font-bold text-slate-950 disabled:opacity-50">Guardar permisos</button></div></section>
    <section className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/60"><div className="flex flex-col gap-3 border-b border-slate-800 p-5 md:flex-row"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar por nombre o correo..." className="flex-1 rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white" /><select value={status} onChange={(e) => setStatus(e.target.value)} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white"><option value="">Todos los estados</option><option value="true">Activos</option><option value="false">Inactivos</option></select><select value={roleFilter} onChange={(e) => setRoleFilter(e.target.value)} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white"><option value="">Todos los roles</option>{roles.map((role) => <option key={role.id_rol} value={role.slug}>{role.nombre}</option>)}</select></div>{loading ? <p className="p-8 text-center text-slate-400">Cargando usuarios...</p> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-800/80 text-xs uppercase text-slate-400"><tr><th className="p-4">Usuario</th><th className="p-4">Correo</th><th className="p-4">Rol</th><th className="p-4">Estado</th></tr></thead><tbody className="divide-y divide-slate-800">{visibleUsers.length === 0 ? <tr><td colSpan={4} className="p-8 text-center text-slate-500">No se encontraron usuarios.</td></tr> : visibleUsers.map((user) => <tr key={user.id_usuario}><td className="p-4 font-semibold">{user.nombre || user.email}</td><td className="p-4 text-slate-400">{user.email}</td><td className="p-4 text-amber-400">{user.roles?.map((item: any) => item.rol?.nombre).filter(Boolean).join(', ') || 'Sin rol'}</td><td className={`p-4 ${user.activo ? 'text-emerald-400' : 'text-red-400'}`}>{user.activo ? 'Activo' : 'Inactivo'}</td></tr>)}</tbody></table></div>}</section>
  </main>;
}
