import { notFound } from 'next/navigation';
import { prisma } from '@/lib/prisma';

export const revalidate = 0;

export default async function ClienteDetailPage({ params }: { params: { id: string } }) {
  const cliente = await prisma.cliente.findUnique({ where: { id_cliente: Number(params.id) }, include: { asesor: true, notas: { orderBy: { fecha: 'desc' } }, actividades: { orderBy: { fecha: 'desc' } } } });
  if (!cliente || cliente.deletedAt) notFound();
  return <main className="max-w-5xl mx-auto p-6 md:p-8 space-y-6"><div className="flex justify-between items-start"><div><p className="text-sm text-amber-400">Cliente #{cliente.id_cliente}</p><h1 className="text-3xl font-extrabold">{cliente.nombre} {cliente.apellido_paterno} {cliente.apellido_materno || ''}</h1><p className="text-slate-400 mt-1">{cliente.estado_cliente || 'nuevo'} · {cliente.asesor ? `${cliente.asesor.nombre} ${cliente.asesor.apellidos}` : 'Sin asesor'}</p></div><a href={`/matching?cliente_id=${cliente.id_cliente}`} className="rounded-lg bg-amber-500 px-4 py-2 text-sm font-bold text-slate-950">Ver matching</a></div><div className="grid gap-4 md:grid-cols-2"><section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6"><h2 className="font-bold">Contacto</h2><dl className="mt-4 space-y-2 text-sm"><div><dt className="text-slate-500">Correo</dt><dd>{cliente.correo || '—'}</dd></div><div><dt className="text-slate-500">WhatsApp</dt><dd>{cliente.whatsapp || cliente.telefono_principal || '—'}</dd></div><div><dt className="text-slate-500">Ubicación</dt><dd>{[cliente.ciudad_busqueda, cliente.estado_busqueda].filter(Boolean).join(', ') || '—'}</dd></div></dl></section><section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6"><h2 className="font-bold">Preferencias</h2><dl className="mt-4 space-y-2 text-sm"><div><dt className="text-slate-500">Presupuesto</dt><dd>{cliente.presupuesto_max ? `$${cliente.presupuesto_max.toLocaleString()}` : '—'}</dd></div><div><dt className="text-slate-500">Tipo</dt><dd>{cliente.tipo_propiedad || '—'}</dd></div><div><dt className="text-slate-500">Habitaciones</dt><dd>{cliente.habitaciones_pa ?? '—'}</dd></div></dl></section></div><section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6"><h2 className="font-bold">Actividad y notas</h2><div className="mt-4 space-y-3 text-sm">{[...cliente.actividades.map((a) => a.descripcion || a.tipo), ...cliente.notas.map((n) => n.contenido)].map((item, i) => <p key={i} className="border-b border-slate-800 pb-2 text-slate-300">{item}</p>)}{cliente.actividades.length === 0 && cliente.notas.length === 0 && <p className="text-slate-500">Sin actividad registrada.</p>}</div></section></main>;
}
