'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';

export default function LoginPage() {
  const router = useRouter();
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(e: React.FormEvent) { e.preventDefault(); setLoading(true); setError(''); try { const response = await fetch('/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password }) }); if (!response.ok) throw new Error((await response.json()).error || 'No fue posible iniciar sesión'); router.push('/dashboard'); router.refresh(); } catch (err) { setError(err instanceof Error ? err.message : 'No fue posible iniciar sesión'); } finally { setLoading(false); } }
  return <main className="min-h-[calc(100vh-4rem)] flex items-center justify-center p-4"><form onSubmit={submit} className="w-full max-w-md rounded-2xl border border-slate-800 bg-slate-900/80 p-8 shadow-2xl space-y-5"><div className="text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-amber-500 font-black text-slate-950">ISO</div><h1 className="mt-3 text-2xl font-extrabold">Iniciar sesión</h1><p className="text-xs text-slate-400 mt-1">Acceso al sistema inmobiliario</p></div>{error && <p className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-center text-sm text-red-300">{error}</p>}<label className="block text-sm text-slate-300">Correo<input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-2.5 text-white outline-none ring-amber-500 focus:ring-2" /></label><label className="block text-sm text-slate-300">Contraseña<input type="password" required value={password} onChange={(e) => setPassword(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-2.5 text-white outline-none ring-amber-500 focus:ring-2" /></label><button disabled={loading} className="w-full rounded-xl bg-amber-500 py-3 font-bold text-slate-950 disabled:opacity-50">{loading ? 'Validando…' : 'Iniciar sesión'}</button></form></main>;
}
